SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS;
SHOW ROLES;

CREATE ROLE IF NOT EXISTS DATAIKU_WRITER;



CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WITH WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;


CREATE DATABASE IF NOT EXISTS DATALAKE;
CREATE SCHEMA IF NOT EXISTS DATALAKE.PUBLIC;

-- Let the role use the warehouse
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATAIKU_WRITER;

-- Let the role use and write in the database/schema
GRANT USAGE ON DATABASE DATALAKE TO ROLE DATAIKU_WRITER;
GRANT USAGE ON SCHEMA DATALAKE.PUBLIC TO ROLE DATAIKU_WRITER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON SCHEMA DATALAKE.PUBLIC TO ROLE DATAIKU_WRITER;

-- Allow data operations
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DATALAKE.PUBLIC TO ROLE DATAIKU_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DATALAKE.PUBLIC TO ROLE DATAIKU_WRITER;

-- Finally, assign the role to the user
GRANT ROLE DATAIKU_WRITER TO USER DATAIKU_USER;



USE ROLE ACCOUNTADMIN;

-- Donne l’accès à la base
GRANT USAGE ON DATABASE DATALAKE TO ROLE DATAIKU_WRITER;

-- (Déjà ok sur le schéma, mais on remet pour être sûr)
GRANT USAGE ON SCHEMA DATALAKE.PUBLIC TO ROLE DATAIKU_WRITER;

-- Accès au warehouse utilisé par Dataiku
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATAIKU_WRITER;

-- (Optionnel mais recommandé) droits DML sur les tables présentes et futures
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA DATALAKE.PUBLIC TO ROLE DATAIKU_WRITER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA DATALAKE.PUBLIC TO ROLE DATAIKU_WRITER;






USE ROLE DATAIKU_WRITER;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DATALAKE;
USE SCHEMA PUBLIC;

-- (si besoin) créer la table
CREATE TABLE IF NOT EXISTS ANNUAL_DEFAULT_RATES (
  ANNEE NUMBER(4,0),
  DEFAILLANCES_ANNEE NUMBER(38,0),
  NB_UL NUMBER(38,0),
  REGION VARCHAR,
  SECTOR VARCHAR,
  TAUX NUMBER(18,6)
);


SHOW GRANTS TO ROLE DATAIKU_WRITER;          -- tu dois voir USAGE sur DATALAKE et COMPUTE_WH
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();







-- contexte
USE ROLE DATAIKU_WRITER;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DATALAKE;
USE SCHEMA PUBLIC;

-- création de la table pour le score de risque
CREATE OR REPLACE TABLE PUBLIC.RISK_SCORE_2026 (
    REGION              VARCHAR,
    SECTOR              VARCHAR,
    ANNEE               NUMBER(4,0),
    REG                 VARCHAR(4),
    A21                 VARCHAR(2),
    TAUX_PRED           FLOAT,
    SCORE_RISQUE        FLOAT
);
